grpc:
  port: "8080"
  users_service_address: "users-service:8080"

# postgres:
#   user: ""
#   name: ""
#   password: ""
#   address: ""

logging:
  isProduction: ${APP_LOGGING_IS_PRODUCTION}
  vectorURL: "http://vector:9880"
